### ISSUE TITLE
Make address in entry details link to directions

### ISSUE THREAD

**Issue by Qrtn** [falling-fruit/falling-fruit-web#144]
**Describe the the feature request**
A clear and concise description of the feature.

**Comment by ezwelty** [comment]
Note that many reverse-geocoded addresses will be vague. For example, [40.6981717, -74.0000815](https://www.google.com/maps/search/40.6981717,-74.0000815) is reverse-geocoded as "Unnamed Road, Brooklyn Heights, NY 11201, USA". Therefore, the coordinates should be used instead of the address for directions, etc.
