### ISSUE TITLE
Change flat type selection in form to hierarchical type filter

### ISSUE THREAD

**Issue by Qrtn** [falling-fruit/falling-fruit-web#230]
## Learning objectives

- Objective

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Todo

## Useful links

- Useful link

**Comment by wbazant** [comment]
I propose we stop planning to do this - I think the flat type selection is better, especially on mobile, where there isn't much space for a complex display like the type filter, and large text and big spaces to click are essential for adding locations on the go.

Since the issue was made, we've started to provide the types in taxonomic order, so the parent type is higher up in the list when they both match (much like a flattened tree) and also #641 will make the search better.

If the current type selection does not work well for users, let's reopen.
