### ISSUE TITLE
Upload photos from device on 'add location'

### ISSUE THREAD

**Issue by tjbutler003** [falling-fruit/falling-fruit-web#368]
I added two trees tonight that I took pictures of a few days ago and had remembered the locations using the satellite image as I planted them myself. When adding the location, I could only take a photo, not add a photo that I had previously taken. I would like to be able to add photos from my device in addition to being able to take a photo in the moment of planting, as I now do a lot of tree planting and don't have the time in the field to upload the location in that moment.

**Comment by ezwelty** [comment]
@tjbutler003 What browser and device are you using? Because on my Android phone, this is what it looks like:

![Screenshot_20231029-084036](https://github.com/falling-fruit/falling-fruit-web/assets/377523/fa0f7735-d295-4f79-9351-555e0d465a5e)

p.s. Uploading existing photos also works in the desktop version.

**Comment by tjbutler003** [comment]
Hi Ethan,
I was using a One phone (android), on google chrome. I can check again. I
might still have the old phone app tho, is there a new app available for
the phone? Or the same as before?
Best, T.J.

**Comment by ezwelty** [comment]
@tjbutler003 It sounds like you are using the mobile app, the repo for which is https://github.com/falling-fruit/falling-fruit-mobile. It does not support adding from library, but is marked as "won't fix" (https://github.com/falling-fruit/falling-fruit-mobile/issues/24) because this new software does.

So yes, I suggest trying out https://beta.fallingfruit.org (this repo) which in principle has support for adding photo from library. (Or the legacy website: https://fallingfruit.org)
