### ISSUE TITLE
mobile: "add new location" state is lost when going to settings and back

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#407]
When adding a location, a user might want to switch to a satellite view or turn labels on.

This issue could be addressed by the click handler for "Map" sometimes routing to the new location page.

It could also be good  to also allow switching to the satellite view when viewing the location - the menu is currently occluded by the drawer, so it would require a different UI design - a drawer from the left?

Related to https://github.com/falling-fruit/falling-fruit-web/issues/406#issuecomment-2180483666.

**Comment by ezwelty** [comment]
"Settings" is not accessible during any location interaction (view, add, edit, review, report) because on desktop the location pane covers the entire left sidebar (including the Settings footer), and on mobile the location drawer comes up from below and covers the entire footer navigation.

The simplest UI fix on desktop would be to prevent the location pane from covering the Settings footer.

On mobile, I would have suggested placing the settings button in the top left, which remains visible when the location drawer is half-open, but this is covered by the instruction message when setting position for new/existing location. Since map switching is most important when setting location position, maybe it is sufficient for now to focus on changing the behavior of the existing Settings footer button: it opens a drawer from the left rather than switching to a new route?

...

Here is how this looks on the current mobile app. Setting in the top left opens a drawer with a close X at the same location (to facilitate quickly opening and closing the drawer). The drawer includes both settings and the location filters, which were split in the current design to accommodate an expanded type filter that remains always visible on desktop (although I note that populating the type counts drives a lot of extra API calls). There is no instruction message when setting position of new location, so it remains accessible. There is no swipe-from-left to open the drawer because I found this to be very fiddly and a button is still needed somewhere to make it clear to users.

<img src="https://github.com/falling-fruit/falling-fruit-web/assets/377523/0a8813ce-1d83-48fc-a304-5b4efe573d6d" width="300px" />

<img src="https://github.com/falling-fruit/falling-fruit-web/assets/377523/af34e1d9-0c6e-4843-943b-cf813c63218c" width="300px" />
