### ISSUE TITLE
(desktop) Allow changing basemap during Add/Edit location

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#421]
Mentioned during #398 but became more prominent after porting the tooltip:
![Screenshot from 2024-07-08 22-29-31](https://github.com/falling-fruit/falling-fruit-web/assets/16976512/fa5d57a8-ba79-44ea-a257-5d17f6f54bf0)

To follow the tooltip's hint about locations being visible from space, the user needs to cancel, go to settings, toggle basemap, and start editing location again.

**Comment by ezwelty** [comment]
> Proposed resolution is to move settings to the left of the top ribbon - Map, About, Settings. Try putting the settings in a full screen like e.g. the sign in page.

@wbazant I like that it better matches the mobile layout, and makes sense if not all settings relate to the map (although language should maybe be moved to the top ribbon). But I can imagine a lot of users fearing that clicking on the top menu will make them lose their place on the map (especially since at the moment all pages have this effect, except "Sign in"), and a full page would look very empty and not allow users to see the result of the setting changes, which is a bonus of having it in the sidebar. Thoughts? Is it not possible to pin Settings to the bottom (or top?) of the map sidebar rather than the top ribbon, but still have it behave this way?

**Comment by wbazant** [comment]
Adding the settings to all other forms is definitely better, I'm not sure why I didn't think about it, thanks! You're right about top ribbon taking us away from the map. The proposed resolution is to then pin it to the bottom and see how it looks under the location / review forms.

**Comment by wbazant** [comment]
The settings are sticky on the live site, I think it looks good!
