### ISSUE TITLE
(mobile) improve filter indicator circle

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#441]
This currently says "99+" for the default selection of all types which is confusing.
#416 suggests to remove it but I think we can save the feature if we show it only when relevant.

Also, show loading states with "..." but only if filters had interactions with them.

**Comment by ezwelty** [comment]
Given the infinite number of possible states that the type filter can have, I just don't see how a number can be useful. Perhaps a binary all vs. filtered, but even this might get tricky, since the goal is ultimately not to select/show all types by default (i.e. type categories: #383).

**Comment by wbazant** [comment]
The number itself isn't useful - I agree the '2' or whatever isn't saying which types were selected - but I think it's more about the yellow dot reminding the user they did something with the filter. If we consider two screenshots of a map, and second one had some filters applied, we don't want them to differ just by some location dots missing - the UI should be reminding the user something has happened - so I think that's the original idea behind the feature.

A dot saying "non-default" will still make sense when the default choice stops being everything, and there can still be a number in it (you can always count the selected types that are on the map) but I can't tell if the number will help or not.

It's easy to axe this at any point - how about keeping the feature for a while with the intent to ask people if they can tell what it means, and then collapse the indicator to all vs. filtered if they don't?

**Comment by wbazant** [comment]
Coming up with a better meaning behind the number is definitely necessary though - I've unticked one field, moved the screen, and ended up with this view of one checked box and 99+ values selected: 

![Screenshot from 2024-08-21 10-28-38](https://github.com/user-attachments/assets/cdbf4174-d221-4111-b111-024599b8d9c9)

**Comment by ezwelty** [comment]
@wbazant Good point. I agree that it is helpful to be reminded that not all of the locations (that would be shown with default settings) are being shown.

> I've unticked one field, moved the screen, and ended up with this view of one checked box and 99+ values selected

Because it is showing the number of selected types in the entire tree. You only see one because "On the map" is checked. If you hit "Deselect all", the number goes to "0", and selecting some types shows the number of selected types.

If the number were made relative to the types present in map bounds (say, the number of types present but not shown by non-default filters), then we would have to call `/types/counts` on each map change also on mobile, which seems like a heavy price to pay.
