### ISSUE TITLE
Geolocation request can permanently spin

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#452]
Happens in my firefox on beta.fallingfruit.org. Not happening on chrome. Found when QAing #425

**Comment by ezwelty** [comment]
I experience different behavior. On my Mac OS 11.7.7:

- Chrome v127.0.6533.100: Works!
- Firefox v130.0.1: Works!
- Safari v16.5: Fails even if I change Location setting for beta.fallingfruit.org from "Ask" to "Allow". Either I get "Geolocation failed: . Please refresh the page and retry" (note the empty error message and thus misplaced punctuation) on every click, or I get the expected behavior when location is denied (goes grey and subsequent clicks toasts info that geolocation was denied).

**Comment by wbazant** [comment]
Closing in favour of #518
