### ISSUE TITLE
Geolocation on Firefox + Android

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#505]
When I use beta.fallingfruit.org on my Android phone, the geolocation doesn't work on my firefox browser (live site works, and beta works on chrome).

I'm not quite sure why, but I'm speculating it's to do with the rate of requests being too high, and firefox stepping in to protect my battery. When I reset permissions, and grant the site 'Always allow' for location, it works briefly, until disabling itself.

**Comment by wbazant** [comment]
Closed in favour of #518

**Comment by wbazant** [comment]
Still happens

**Comment by wbazant** [comment]
Extra clue: it now happens intermittently, and can be reliably triggered by pressing the geolocation button twice quickly.

Maybe Firefox blocks if a geolocation request that didn't get answered yet is followed by another request?

**Comment by ezwelty** [comment]
@wbazant I can reproduce the behavior you describe on my Android phone with the Firefox app. But for me it also happens if I make a request and start tracking, then stop tracking, then restart the procedure shortly after (location access is then switched to 'Block' and I have to switch it back to 'Allow' manually). Just guessing here: maybe once the location service is established, we need to keep the connection alive (but stop querying location) if the user turns off tracking?
