### ISSUE TITLE
live values for "millions of locations" and other

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit-web#528]
I realised we need this for #492. The live site tells you exactly that there are e.g. "distributed over 1,667,093 locations " and this is a dynamic value, since the locale file says "{locations} locations"

@ezwelty would you update the issue with the details of the live site knows this?

**Comment by ezwelty** [comment]
See my https://github.com/falling-fruit/falling-fruit-web/pull/526#issuecomment-2423091149. I wrote the numbers out of existence in the revised English text so that the beta wouldn't need to query the API (and because the exact numbers don't really matter). Will you miss this element or are you okay closing as won't fit?

**Comment by wbazant** [comment]
Won't miss them! :)
