### ISSUE TITLE
Unable to add items on iPhone

### ISSUE THREAD

**Issue by taitems** [falling-fruit/falling-fruit-web#573]
I've been amassing photos with the goal of giving the UI a good test when I attempt to add 31 new locations.

Unfortunately the moment I try to add something on mobile I am hit with this message. Redacted for privacy.

![image](https://github.com/user-attachments/assets/dcda2253-dea7-4ee7-bdcd-93f803531c8c)

Information:
- iPhone 12
- Location permissions granted
- Occurs on both 5G and Wifi
- Occurs in both Safari and added as a home screen app
- Some Safari ad blockers are installed but these are generally pretty ineffective

**Comment by wbazant** [comment]
I think the -213 in the URL is the reason - would you help me debug this?
- use geolocation, then try to add a new location
- search for a place like "Melbourne", then scroll in to wherever you are, then try add a new location
- attempt to add a new location in a place where both geo-coordinates are positive - maybe a non-edible dumpster in Parliament Square, London, or something like that - no need to actually submit it

I'm guessing you're doing the first one and the other two will work, and then I'll also know what to fix - I'll get my browser to pretend I'm in Australia, but it'll be hard for me to test the iPhone part so it'll be helpful if you'll help me check my assumptions here!

**Comment by wbazant** [comment]
Actually, the browser doesn't let me pretend I'm at those coordinates: 
![Screenshot from 2024-11-08 12-10-38](https://github.com/user-attachments/assets/b8b273f2-9597-4acb-b209-7d8f31704d09)

and I thought about it more - I'm not sure where the -213 longitude comes from, but my geolocation guess is probably useless since the view is ultimately changed by Google Maps, and their own docs say the range is -180,180. So somehow, center.lng() in `src/components/map/MapPage.js` must have returned that value. I've proposed a workaround (but if you help me narrow it down @taitems , we might fix it be able to fix it better).

**Comment by taitems** [comment]
Can confirm the fix has worked, testing with Melbourne, VIC and Carnegie, VIC. 

Unfortunately I'm hit by the other upload bug where the image fails but the entry is created. It just takes an app reload to appear. 

![image](https://github.com/user-attachments/assets/dc5c3d6c-e6cd-4335-8730-9ab8e1f7f249)

**Comment by wbazant** [comment]
Was that on beta.fallingfruit.org? Or you're running locally?

**Comment by taitems** [comment]
That was the beta site, yes. I'm still yet to pull down the source and run it locally.
